name: TrentsArtwork
favicon: null
layout_spectrum: 0.90198
typography_spectrum: 0.15036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.35171058564446867
  saturation: 0.6616574239451438
  rhythmicContrast: 0.457949957344681
purpose: []
